// Generates src/palette.css from @radix-ui/colors (the source of truth; no hand-picked hex).
// Radix ships its dark scales under `.dark`; this app themes with [data-theme="dark"],
// so we re-emit the same values under our selector. Run: node scripts/gen-palette.mjs
import * as rc from "@radix-ui/colors";
import { writeFileSync } from "node:fs";

// Scales in use. Slot names (left) are the app's existing data-hue keys.
export const SCALES = ["jade", "blue", "plum", "ruby", "cyan", "gold", "sand"];
export const SLOTS = {
  brand: "jade",   // primary: buttons, dock pill, segment, progress
  blue: "blue",    // CoreSat, web sources, plan
  violet: "plum",  // Mega, AI, market data
  emerald: "jade", // Value, buy/trade/selected, SEC
  pink: "ruby",    // Swing, sell/rejected/risk, trend
  cyan: "cyan",    // RiskOff, tax, hold
  gold: "gold",    // book
  slate: "sand",   // neutral, X sources, sources
};
// Solid step carrying white text: lowest Radix step (9→11) with white >= 4.5:1 (WCAG AA).
export const SOLID_STEP = { jade: 11, blue: 11, plum: 9, ruby: 11, cyan: 11, gold: 11, sand: 11 };

const vars = (obj, name, alpha = false) =>
  Object.values(obj).map((v, i) => `  --${name}-${alpha ? "a" : ""}${i + 1}: ${v};`).join("\n");

let light = [], dark = [], fixed = [];
for (const s of SCALES) {
  light.push(vars(rc[s], s), vars(rc[`${s}A`], s, true));
  dark.push(vars(rc[`${s}Dark`], s), vars(rc[`${s}DarkA`], s, true));
  const solid = Object.values(rc[s])[SOLID_STEP[s] - 1];
  const accent = Object.values(rc[s])[8];
  fixed.push(`  --${s}-solid: ${solid};   /* ${s} step ${SOLID_STEP[s]} (light), white text AA */`);
  fixed.push(`  --${s}-accent: ${accent};  /* ${s} step 9, non-text accents */`);
}
light.push(vars(rc.whiteA, "white", true), vars(rc.blackA, "black", true));

const slotCss = Object.entries(SLOTS)
  .map(([k, s]) => `  --slot-${k}: ${s};`).join("\n");

const out = `/* GENERATED by scripts/gen-palette.mjs from @radix-ui/colors v3. Do not edit by hand.
   Scales: ${SCALES.join(", ")}. Steps: 1-2 app bg, 3-5 subtle fills, 6-8 borders,
   9-10 solid accents, 11 low-contrast text, 12 high-contrast text. a1-a12 = alpha variants. */
:root {
${light.join("\n")}
${fixed.join("\n")}
}
[data-theme="dark"] {
${dark.join("\n")}
}
`;
writeFileSync(new URL("../src/palette.css", import.meta.url), out);
console.log("wrote src/palette.css", out.length, "bytes");
